// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.OrderSagaOrchestrator.Persistence;

namespace Shopping.OrderSagaOrchestrator.Migrations
{
    [DbContext(typeof(OrderSagaContext))]
    [Migration("20220118083025_UpdateOrderStateDataModelToSupportOptimisticConcurrency")]
    partial class UpdateOrderStateDataModelToSupportOptimisticConcurrency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shopping.OrderSagaOrchestrator.StateMachine.OrderStateData", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CustomerUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OrderCancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("OrderTotalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PaymentCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CorrelationId");

                    b.ToTable("OrderStateData");
                });
#pragma warning restore 612, 618
        }
    }
}
