version: '3.4'

services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"

  identitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: identitydb
    environment:
      SA_PASSWORD: "September24#"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - 1444:1433

  shopping.idp:
    image: ${DOCKER_REGISTRY-}shoppingidp
    container_name: shopping.identity
    build:
      context: Src/
      dockerfile: Identity/Shopping.IDP/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- IdentityIssuer=https://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:8021
      - "ConnectionStrings:IdentityDb=Server=identitydb;Database=IdentityDb;User Id=sa;Password=September24#;"
    ports:
      - "8021:80"
    depends_on:
      - identitydb

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.api
    build:
      context: Src/
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
      - IdentityProviderSettings:IdentityServiceUrl=https://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:8021
    ports:
      - "8000:80"
    depends_on:
      - catalogdb
      - shopping.idp

  