on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_ACR_SP_CREDENTIALS }}
            #client-id: ${{ secrets.AZURE_ACR_SP_CLIENT_ID }}
            #tenant-id: ${{ secrets.AZURE_ACR_SP_TENANT_ID }}
            #subscription-id: ${{ secrets.AZURE_ACR_SP_SUBSCRIPTION_ID }}
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/web.razor:${{ github.sha }} -f ./Src/Clients/Shopping.Razor/DockerFile
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/web.razor:${{ github.sha }}
        
