on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_ACR_SP_CREDENTIALS }}
            #client-id: ${{ secrets.AZURE_ACR_SP_CLIENT_ID }}
            #tenant-id: ${{ secrets.AZURE_ACR_SP_TENANT_ID }}
            #subscription-id: ${{ secrets.AZURE_ACR_SP_SUBSCRIPTION_ID }}
        - name: 'Login to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: 'Build and push web.razor image'
          uses: docker/build-push-action@v2
          with:
            context: ./Src
            file: ./Src/Clients/Shopping.Razor/Dockerfile
            push: true
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/web.razor:${{ github.sha }}
          #run: |
           # cd ./Src
            #docker build -f ./Clients/Shopping.Razor/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/web.razor:${{ github.sha }} .
            #docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/web.razor:${{ github.sha }}
        #- name: 'Build and push identityprovider image'
        # run: |
        #    docker build ./Src/Identity/Shopping.IDP -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/identityprovider:${{ github.sha }}
        #    docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/identityprovider:${{ github.sha }}
        
