name: Build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v2
      with:	
        dotnet-version: 3.1.x
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Src/MicroservicesShop.sln
    - name: Build
      run: dotnet build ./Src/MicroservicesShop.sln --no-restore
    - name: Test
      #run: dotnet test ./Src/MicroservicesShop.sln --no-build --verbosity normal
      run: dotnet test ./Src/Tests/Shopping.UnitTests/Shopping.UnitTests.csproj --no-build --verbosity normal
