name: Build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
     - '!Src/Identity/Shopping.IDP/certs/**'
    #paths-ignore:
     # - 'certs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Src/MicroservicesShop.sln
    - name: Build
      run: dotnet build ./Src/MicroservicesShop.sln --no-restore
    - name: Test
      run: dotnet test ./Src/Tests/Shopping.UnitTests.csproj --no-build --verbosity normal
