name: build and test

on:
  push:
    branches: [ "main" ]
    paths:
    - '**.cs'               # run if there is any change to .cs file
    - '**.csproj'
    - '**.yml'
    - '!**.pfx' # ignore this file (example)
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v2
      with:	
        dotnet-version: 3.1.x
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Src/MicroservicesShop.sln
    - name: Build
      run: dotnet build ./Src/MicroservicesShop.sln --no-restore
    - name: Run unit tests
      run: dotnet test ./Src/Tests/Shopping.UnitTests --no-build --verbosity normal
    - name: Run integration tests
      run: dotnet test ./Src/Tests/Shopping.IntegrationTests  --no-build --verbosity normal
    - name: Run SpecFlow BDD tests
      #run: dotnet test ./Src/Tests/Shopping.BddTests/Shopping.BddTests.csproj --no-build --verbosity normal
      uses: ./Src/Tests/Shopping.BddTests
      with: 
        test-assembly-path: Src/Tests/Shopping.BddTests/bin/Debug/net5.0
        test-assembly-dll: Shopping.BddTests.dll
        test-execution-json: TestExecution.json
        output-html: MyTestResults.html
        framework: net5.0
        no-build: true
        upload-artifact: false
