name: build and test

on:
  push:
    branches: [ "main" ]
    paths:
    - '**.cs'               # run if there is any change to .cs file
    - '**.csproj'
    - '**.yml'
    #- '!github-actions/DotNet.GitHubAction/CODE_METRICS.md' # ignore this file (example)
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
    - name: Display dotnet version
      run: dotnet --version
    - name: Restore dependencies
      run: dotnet restore ./Src/MicroservicesShop.sln
    - name: Build
      run: dotnet build ./Src/MicroservicesShop.sln --no-restore
    - name: Run unit tests
      run: dotnet test ./Src/Tests/Shopping.UnitTests --no-build --verbosity normal
    - name: Run integration tests
      run: dotnet test ./Src/Tests/Shopping.IntegrationTests --no-build --verbosity normal
    
